name: Deploy to GitHub Pages
permissions:
  pages: write
  id-token: write
  contents: read
on:
  push:
    branches:
      - main

jobs:
  call_workflow:
    uses: FranCalveyra/conc-summary/.github/workflows/cd.yml@main
